### ISSUE TITLE
Treatment of NAs in gghistostats with regard to central tendency measures

### ISSUE THREAD

**Issue by ethulin** [IndrajeetPatil/ggstatsplot#33] opened 2018-06-15 14:37 UTC
In gghistostats, If you give a vector with NAs, it will still plot the histogram, but it won't draw the mean/median. Might be worth making consistent what the function will accept to plot and what it will display central tendency for.

(As noted on twitter, "The `na.rm = TRUE` arguments are indeed missing for the `geom_line()` function in `gghistostats` and that's why it's behaving this way.")

**Comment by IndrajeetPatil** [comment] 2018-06-15 15:48
Actually, now that I've looked at the code more carefully, this shouldn't be happening because I had already included `na.rm = TRUE` in those `geoms`.

https://github.com/IndrajeetPatil/ggstatsplot/blob/128e6f19f44792515769039e2df6cc8e176f0e87/R/gghistostats.R#L442-L450

Can you post a reproducible example here?

**Comment by IndrajeetPatil** [comment] 2018-06-20 14:09
I am closing this because I can't reproduce this error and no reprex has been provided.

``` r

# creating a vector using NAs
x <- c(2, 3, 4, 5, 5, 7, 8, 5, NA, NA, NA)

# creating a histogram
ggstatsplot::gghistostats(x = x, centrality.para = "mean")
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/2URUJoE.png)

Created on 2018-06-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Closed** 2018-06-20 14:09 UTC
Labels: reprex
