### ISSUE TITLE
GLM issue ("coefficients" not "estimate" output) and request for ggcoefstats (remove certain estimates from visualization)

### ISSUE THREAD

**Issue by IsadoraBM** [IndrajeetPatil/ggstatsplot#460] opened 2020-10-09 02:26 UTC
Issue: Using rms::GLM but ggcoefstats(x = model) throws out an error that `The tidy dataframe *must* contain column called 'estimate'. Check the tidy output using argument 'output = 'tidy'.` Using `names(model)  <- "estimate"` to change the name works on the model output but error persists. 

Request: feature to specify which estimates to display from model (e.g remove controls from condensed visualization) similar to coefplot's `predictors` argument.

**Comment by IndrajeetPatil** [comment] 2020-10-09 07:09
Hmm, I actually can't reproduce this error:

``` r
set.seed(123)
library(ggstatsplot)
library(rms)

## Dobson (1990) Page 93: Randomized Controlled Trial :
counts <- c(18,17,15,20,10,20,25,13,12)
outcome <- gl(3,1,9)
treatment <- gl(3,3)
f <- glm(counts ~ outcome + treatment, family=poisson())

ggstatsplot::ggcoefstats(f)
```

![](https://i.imgur.com/9CiR07K.png)

<sup>Created on 2020-10-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment] 2020-10-09 07:15
As for the second issue, I would prefer not to support specifying exactly which predictors to show. This is at any case easier for the user to do. There are two options:

1. If there are too many effects, maybe only display the significant ones:

<img width="1372" alt="Screenshot 2020-10-09 at 09 14 38" src="https://user-images.githubusercontent.com/11330453/95554108-e94f2f00-0a0f-11eb-88ee-c69481fa515e.png">

2. Simply select the predictors you want to display and then enter a dataframe with the selected ones:

``` r
set.seed(123)
library(tidyverse)
library(rms)

## Dobson (1990) Page 93: Randomized Controlled Trial :
counts <- c(18, 17, 15, 20, 10, 20, 25, 13, 12)
outcome <- gl(3, 1, 9)
treatment <- gl(3, 3)
f <- glm(counts ~ outcome + treatment, family = poisson())

# only showing treatment effects
broomExtra::tidy_parameters(f) %>%
  dplyr::filter(!grepl(pattern = "outcome", x = term, ignore.case = TRUE)) %>%
  ggstatsplot::ggcoefstats(., statistic = "z", exclude.intercept = FALSE)
```

![](https://i.imgur.com/wNO794k.png)

<sup>Created on 2020-10-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IsadoraBM** [comment] 2020-10-09 17:31
glm is the base-R function, in rms it is capitalized so rms::Glm()
Could you try that?

**Comment by IndrajeetPatil** [comment] 2020-10-09 18:51
Oops, sorry about that. 

I can reproduce this now.

``` r
set.seed(123)
library(ggstatsplot)
library(rms)

## Dobson (1990) Page 93: Randomized Controlled Trial :
counts <- c(18,17,15,20,10,20,25,13,12)
outcome <- gl(3,1,9)
treatment <- gl(3,3)
f <- Glm(counts ~ outcome + treatment, family=poisson())

broomExtra::tidy_parameters(f)
#> NULL
```

<sup>Created on 2020-10-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment] 2020-10-11 11:00
Closed in favor of https://github.com/easystats/parameters/issues/313

**Closed by IndrajeetPatil** 2020-10-11 11:00 UTC
Labels: enhancement 🔥, question ❓
