### ISSUE TITLE
Line of statistics is trimmed after the 4.0.4 update

### ISSUE THREAD

**Issue by teindor** [IndrajeetPatil/ggstatsplot#529] opened 2021-02-18 20:00 UTC
when using the ggstatsplot::ggscatterstats function, the line of stat (upper left) is trimmed such that the stat shows only from the df onward.

that was my line of code. It produces the plot, but as mentioned, the text does not appear correctly.

s3.f1 = ggstatsplot::ggscatterstats(
  type = "p",
  data = u.s3, # dataframe from which variables are taken
  x = anxiety, # predictor/independent variable
  y = Dp, # dependent variable
  xlab = "Parent's attachment anxiety", # label for the x-axis
  ylab = "Sensitivity in lie detection (Dprime)", # label for the y-axis
  marginal.type = "density", # type of plot for marginal distribution
  xfill = "#CC79A7", # fill for marginals on the x-axis
  yfill = "#009E73", # fill for marginals on the y-axis
)

**Comment by IndrajeetPatil** [comment] 2021-02-18 20:02
Duplicate of https://github.com/IndrajeetPatil/ggstatsplot/issues/529.

Run:

```r
remotes::install_github("IndrajeetPatil/statsExpressions")
```

**Closed** 2021-02-18 20:03 UTC
