### ISSUE TITLE
grouped_ggbetweenstats grouped instead of 'faceted'

### ISSUE THREAD

**Issue by KZacharaki** [IndrajeetPatil/ggstatsplot#651] opened 2021-08-11 10:48 UTC
Hi! thank you for this amazing package. Is it very easy to use!
I am trying to plot violin plots according to a grouping variable. Although, the option of grouped_ggbetweenstats is great, I would prefer to have the abilitity to choose if I want the grouping variable to divide the violin plots into two facets or have the option of position dodge so that all of my violin plots are in the same axes.

Thank you!

**Comment by IndrajeetPatil** [comment] 2021-08-11 10:51
Duplicate of #311, #410

Closing in favor of #500

**Closed by IndrajeetPatil** 2021-08-11 10:51 UTC

**Comment by IndrajeetPatil** [comment] 2021-08-11 10:58
And to have a uniform axis, see FAQ-7

https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/faq.html#7-how-can-i-have-uniform-y-axes-ranges-in-grouped-functions-
