### ISSUE TITLE
Coefficients order 2

### ISSUE THREAD

**Issue by xieguagua** [IndrajeetPatil/ggstatsplot#156] opened 2019-02-02 15:07 UTC
Thanks for your answer.
Here is the example .
If We run:
polr.mod <- MASS::polr(formula = Sat ~ Infl + Type + Cont,
weights = Freq,
data = housing)

summary(polr.mod )

![image](https://user-images.githubusercontent.com/31589570/52165718-3fe66f00-273f-11e9-99b3-5089701ea199.png)

then plot ,

ggstatsplot::ggcoefstats(x = polr.mod, 
                         coefficient.type = "both",
                         title = "ordered logistic or probit regression",
                         subtitle = "using `MASS` package")

#the Coefficients order is not as same as in "summary",
#Could the plot order  just as same as the summary ?

![image](https://user-images.githubusercontent.com/31589570/52165638-52ac7400-273e-11e9-973f-91fbf0018db7.png)
![image](https://user-images.githubusercontent.com/31589570/52165655-8daea780-273e-11e9-98f6-00a0ee480a29.png)

**Comment by IndrajeetPatil** [comment] 2019-02-02 15:13
What do you get if you run the following code?

```r
broom::tidy(polr.mod)
```

**Comment by IndrajeetPatil** [comment] 2019-02-07 00:50
Duplicate of #154

**Closed by IndrajeetPatil** 2019-02-07 00:50 UTC
