### ISSUE TITLE
Small p Value Annotation

### ISSUE THREAD

**Issue by DarioS** [IndrajeetPatil/ggstatsplot#428] opened 2020-05-12 02:00 UTC
In the example, there is p = < 0.001 Should the equals sign be omitted if there is an inequality?

**Comment by IndrajeetPatil** [comment] 2020-05-13 10:57
Duplicate of https://github.com/IndrajeetPatil/ipmisc/issues/9

**Closed by IndrajeetPatil** 2020-05-13 10:57 UTC
