### ISSUE TITLE
"vector size cannot be NA/NaN error" in ggbetweenstats with a specific number of samples

### ISSUE THREAD

**Issue by mestaki** [IndrajeetPatil/ggstatsplot#534] opened 2021-03-02 10:45 UTC
I have an odd issue which seems to be specific with my dataset as I can't create a reprex for.

```
library(tidyverse)
df_long %>% 
  ggstatsplot::ggbetweenstats(
    data = .,
    x = periods,
    y = hours)
```

which gives this error:

```
Error in sample.int(length(x), size, replace, prob) : 
  vector size cannot be NA/NaN
```

I have no problem plotting the same dataset with base or ggplot2 alone. The data is a simple tibble with 2 cols

```
> df_long
# A tibble: 32,190 x 2
   periods        hours
   <chr>          <dbl>
 1 scan_to_qpcr    15.2
 2 qpcr_to_review  15.2
 3 scan_to_epic    15.2
 4 scan_to_qpcr    14.2
 5 qpcr_to_review  14.2
 6 scan_to_epic    14.2
 7 scan_to_qpcr    14.8
 8 qpcr_to_review  14.8
 9 scan_to_epic    14.8
10 scan_to_qpcr    13.8
# … with 32,180 more rows
```
There isn't anything unique as far as I can tell about the data itself

```
str(df_long)
tibble [32,190 × 2] (S3: tbl_df/tbl/data.frame)
 $ periods: chr [1:32190] "scan_to_qpcr" "qpcr_to_review" "scan_to_epic" "scan_to_qpcr" ...
 $ hours  : num [1:32190] 15.2 15.2 15.2 14.2 14.2 ...

df_long$periods %>% table()
qpcr_to_review   scan_to_epic   scan_to_qpcr 
         10730          10730          10730 

df_long$hours %>% summary()
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -11.49   16.63   21.43   22.86   27.95   95.93 
```

and all NAs have been removed:

```
is.na(df_long) %>% sum()
[1] 0
```

The peculiar thing is, the problem goes away if I plot up to the first 10,042 rows, so using `df_long[1:10942,]` works but `df_long[1:10943,] gives the mentioned error. Plotting the other half also works fine:
 
```
df_long[10000:nrow(df_long),] %>% 
  ggstatsplot::ggbetweenstats(
    data = .,
    x = periods,
    y = hours)
```
 
I can't seem to reproduce this error however, since the below works as expected

```
dat <- tibble(counts= rnorm(21000, mean = 22, sd = 9), 
       groups =rep(letters[1:3], each=7000))

dat %>% 
  ggstatsplot::ggbetweenstats(
    data = .,
    x = groups,
    y = counts)
```

Any thoughts on what could be causing this? 
Fantastic package by the way!

**Comment by IndrajeetPatil** [comment] 2021-03-02 11:26
Hmm, puzzling. Without data, this is indeed going to be hard to diagnoze. 

When you run the function and get the error, can you please run

```r
traceback()
```

and then report the output here?

That will give me some idea about the nature of the error.

**Comment by mestaki** [comment] 2021-03-02 21:14
Thanks @IndrajeetPatil,
Puzzling indeed!
The traceback output is quite large and I don't have permission to share the data publically at the moment, happy to share via DM. Ok to send to your email on your GH profile?

**Comment by IndrajeetPatil** [comment] 2021-03-02 21:34
Sure, you can share the data with me here:
patilindrajeet.science@gmail.com

Only share the columns required for the function.

**Comment by IndrajeetPatil** [comment] 2021-03-03 06:32
Thanks! I can reproduce this and will have a closer look.

In the meantime, you can get the function to work by setting `bf.message = FALSE`.

**Comment by mestaki** [comment] 2021-03-03 07:18
Glad to hear you can reproduce it on your end. Suppressing the bf.message works great for what I need in the meantime! Thank you very much.

**Comment by IndrajeetPatil** [comment] 2021-03-03 07:20
Cool, I am closing this for now since the issue lies with `performance` package, and I am discussing with them how to resolve it.

**Closed by IndrajeetPatil** 2021-03-03 07:20 UTC
Labels: bug 🐜
