### ISSUE TITLE
https://stackoverflow.com/questions/65395072/non-finite-value-supplied-in-ggstatsplot

### ISSUE THREAD

**Issue by cqneosun** [IndrajeetPatil/ggstatsplot#558] opened 2021-04-07 09:48 UTC
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

Brief description of the problem

```r
# insert reprex here
```
https://stackoverflow.com/questions/65395072/non-finite-value-supplied-in-ggstatsplot

**Comment by IndrajeetPatil** [comment] 2021-04-07 10:00
Duplicate of https://github.com/IndrajeetPatil/ggstatsplot/issues/498

**Closed by IndrajeetPatil** 2021-04-07 10:00 UTC
